apiVersion: v1
kind: Secret
metadata:
  name: {{ template "gitlab.fullname" . }}
  labels:
    app: {{ include "gitlab.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  rootPassword: {{ .Values.gitlab.env.rootPassword | b64enc | quote }}
  dbUser: {{ .Values.gitlab.env.db.user | b64enc | quote }}
  dbPassword: {{ .Values.gitlab.env.db.pass | b64enc | quote }}
  dbKeyBase: {{ .Values.gitlab.env.secrets.dbKeyBase | b64enc | quote }}
  secretKeyBase: {{ .Values.gitlab.env.secrets.secretKeyBase | b64enc | quote }}
  otpKeyBase: {{ .Values.gitlab.env.secrets.otpKeyBase | b64enc | quote }}
