{{- if .Values.postgresql.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ template "gitlab.fullname" . }}-postgreql
  labels:
    app: {{ template "gitlab.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: postgreql
spec:
  accessModes:
  - {{ .Values.postgresql.persistence.accessMode | quote }}
  storageClassName: {{ .Values.postgresql.persistence.storageClassName | quote }}
  resources:
    requests:
      storage: {{ .Values.postgresql.persistence.size | quote }}
{{- end }}